service: image-process-lambda

frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

package:
  exclude:
    - .idea/**
    - __pycache__/**
    - .pytest_cache/**
    - tesseract/**
    - venv/**
    - env/**
    - node_modules
    - build_tesseract.sh
    - Dockerfile
    - lambda_event.json
    - requirements.txt
    - serverless.yml
    - test.jpg
    - test_handler.py
    - use_ocr_as_a_service.py

functions:
  create:
    handler: receipts-api.handler.create
    events:
      - http:
          path: posts/create
          method: post
  get:
    handler: receipts-api.handler.get
    events:
      - http:
          path: posts/get
          method: get
  all:
    handler: receipts-api.handler.all
    events:
      - http:
          path: posts/all
          method: get

resources: 
    Resources:
      postsTable: 
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: posts
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: N
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
  
plugins:
- serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true