Resources:
  ReceiptsTable: 
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: attachment-store
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: business_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: business_id
          KeyType: HASH
        - AttributeName: user_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  ReceiptsTable:
    Value:
      Ref: ReceiptsTable